remove:
	rm out.json 
json:
	flex trabalhoflex.l
	gcc -o trabalhoflex lex.yy.c
	./trabalhoflex

all:
	rm out.json 
	flex trabalhoflex.l
	gcc -o trabalhoflex lex.yy.c
	./trabalhoflex

open:
	open out.json




	